export const PROJECTS = [
  {
    id: 'atrion',
    number: '01',
    name: 'ATRION',
    type: 'Cognitive Runtime',
    desc: 'Cognitive resilience runtime',
    tags: ['TypeScript', 'Node.js', 'Vector Ops'],
    link: 'https://github.com/laphilosophia/atrion',
  },
  {
    id: 'nabu',
    number: '03',
    name: 'NABU',
    type: 'Cognitive Substrate',
    desc: 'Physics engine for synthetic cognition.',
    tags: ['Typescript', 'HNSW', 'Phase Graph'],
    link: 'https://github.com/laphilosophia/nabu',
  },
  {
    id: 'mindfry',
    number: '03',
    name: 'MINDFRY',
    type: 'Cognitive DB Engine',
    desc: 'Cognitive ephemeral graph database',
    tags: ['RUST', 'Ephemeral', 'Consciousness'],
    link: 'https://github.com/laphilosophia/mindfry',
  },
  {
    id: 'tracehound',
    number: '04',
    name: 'TRACEHOUND',
    type: 'Security buffer',
    desc: 'Deterministic runtime security.',
    tags: ['Typescript', 'Nodejs', 'Commercial', 'Security'],
    link: 'https://tracehound.vercel.app/',
  },
  {
    id: 'clearhold',
    number: '05',
    name: 'CLEARHOLD',
    type: 'Trust-based gateway',
    desc: 'Payment-adjacent execution & risk infrastructure',
    tags: ['Typescript', 'Nodejs', 'Commercial', 'Escrow'],
    link: 'https://clearhold.vercel.app/',
  },
  {
    id: 'tcr-tools',
    number: '06',
    name: 'TCR.TOOLS',
    type: 'Temporal coordination runtime',
    desc: 'Deterministic coordination layer',
    tags: ['Typescript', 'Forensic', 'Commercial'],
    link: 'https://tcr-tools.vercel.app/',
  },
  {
    id: 'volta',
    number: '07',
    name: 'VOLTA',
    type: 'Headless Platform Engine',
    desc: 'Headless Platform Engine for LC/NC applications',
    tags: ['Typescript', 'LC/NC', 'Engine'],
    link: 'https://github.com/laphilosophia/volta-next',
  },
]
