export const PROJECTS = [
  {
    id: 'atrion',
    number: '01',
    name: 'ATRION',
    type: 'Cognitive Runtime',
    desc: 'Cognitive Resilience Runtime',
    tags: ['TypeScript', 'Node.js', 'Vector Ops'],
    link: 'https://github.com/laphilosophia/atrion',
  },
  {
    id: 'mindfry',
    number: '02',
    name: 'MINDFRY',
    type: 'Memory Layer',
    desc: 'Consciousness-inspired memory graph.',
    tags: ['WASM', 'HNSW', 'Phase Graph'],
    link: 'https://github.com/laphilosophia/mindfry',
  },
  {
    id: 'tracehound',
    number: '03',
    name: 'TRACEHOUND',
    type: 'Security Buffer',
    desc: 'Deterministic runtime security for modern applications.',
    tags: ['Typescript', 'Nodejs', 'Commercial', 'Security'],
    link: 'https://tracehound.vercel.app/',
  },
  {
    id: 'clearhold',
    number: '04',
    name: 'CLEARHOLD',
    type: 'Trust-based Gateway',
    desc: 'Payment-adjacent execution & risk infrastructure',
    tags: ['Typescript', 'Nodejs', 'Commercial', 'Escrow'],
    link: 'https://clearhold.vercel.app/',
  },
  {
    id: 'tcr-tools',
    number: '05',
    name: 'TCR.TOOLS',
    type: 'Temporal Coordination Runtime',
    desc: 'Deterministic intent resolution, causal timelines, and time-travel debugging.',
    tags: ['Typescript', 'Forensic', 'Commercial'],
    link: 'https://tcr-tools.vercel.app/',
  },
  {
    id: 'strime',
    number: '06',
    name: 'STRIME',
    type: 'JSON Engine',
    desc: 'Streaming JSON projection engine - extract fields at multi-gigabit speeds with O(1) memory.',
    tags: ['Typescript', 'JSON'],
    link: 'https://github.com/laphilosophia/strime',
  },
]
